-- Fase 0, Bloco 3/4: entitlements resolved from config instead of a hardcoded
-- constant, plus the AI cost ledger and generalized content cache.
--
-- NOT APPLIED. This file was generated by hand (no DATABASE_URL is available
-- in this environment, and the Postgres these tables would land in is shared
-- production infra for another product — see docs/ARCHITECTURE.md §5). It
-- only ADDS new tables; nothing existing is altered, renamed or dropped.
-- All three tables are @@map-prefixed with "quibly_" so they cannot collide
-- with the neighboring product's tables, same reasoning as "captured_lessons".

-- CreateTable
CREATE TABLE "quibly_entitlements" (
    "id" UUID NOT NULL,
    "plan" "plan" NOT NULL,
    "key" TEXT NOT NULL,
    "limit_value" INTEGER,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quibly_entitlements_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "quibly_entitlements_plan_key_key" ON "quibly_entitlements"("plan", "key");

-- CreateTable
CREATE TABLE "quibly_ai_usage_ledger" (
    "id" UUID NOT NULL,
    "user_id" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "task" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "model" TEXT NOT NULL,
    "input_tokens" INTEGER NOT NULL DEFAULT 0,
    "output_tokens" INTEGER NOT NULL DEFAULT 0,
    "estimated_cost_usd" DECIMAL(10,6) NOT NULL DEFAULT 0,
    "cache_hit" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quibly_ai_usage_ledger_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "quibly_ai_usage_ledger_user_id_date_idx" ON "quibly_ai_usage_ledger"("user_id", "date");

-- CreateIndex
CREATE INDEX "quibly_ai_usage_ledger_date_idx" ON "quibly_ai_usage_ledger"("date");

-- CreateTable
CREATE TABLE "quibly_ai_content_cache" (
    "id" UUID NOT NULL,
    "content_hash" TEXT NOT NULL,
    "task" TEXT NOT NULL,
    "language" TEXT NOT NULL,
    "result" JSONB NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "quibly_ai_content_cache_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "quibly_ai_content_cache_content_hash_key" ON "quibly_ai_content_cache"("content_hash");

-- CreateIndex
CREATE INDEX "quibly_ai_content_cache_task_idx" ON "quibly_ai_content_cache"("task");
